services:
  minecraft:
    image: itzg/minecraft-bedrock-server:latest
    container_name: minecraft-bedrock
    network_mode: host
    environment:
      EULA: "TRUE"
      SERVER_NAME: "${SERVER_NAME:-Bedrock Server}"
      GAMEMODE: "${GAMEMODE:-survival}"
      DIFFICULTY: "${DIFFICULTY:-normal}"
      ALLOW_LIST: "${ALLOW_LIST:-true}"
      ONLINE_MODE: "${ONLINE_MODE:-true}"
    volumes:
      - ./data:/data
    restart: unless-stopped
