services:
  minecraft:
    image: itzg/minecraft-server:latest
    # container_name: java
    network_mode: host
    environment:
      EULA: "TRUE"
      TYPE: "PURPUR"
      # VERSION: "LATEST"
      # コンテナ内部のrcon-cliから管理コマンドを実行するために有効化する。
      ENABLE_RCON: "TRUE"
      # MEMORY: 1G

      # ENABLE_WHITELIST: "TRUE"
      SERVER_PORT: "25565"
    volumes:
      - ./data:/data
    restart: unless-stopped
